---
title: "Module 8 Project Report"
author: "Jaan Selod"
date: "2023-11-17"
output: html_document
bibliography: BIOL3140.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rgbif)
library(tidyverse)
library(MuMIn)
library(rnoaa)
library(data.table)
library(ggmap)
library(usmap)
library(sf)
library(magick)
library(cowplot)
library(lme4)
library(car)
library(data.table)
```

```{r querying GBIFs API, echo=FALSE, cache = TRUE}
species <- c("Piranga olivacea", "Leiothlypis ruficapilla", "Dolichonyx oryzivorus", "Megaceryle alcyon","Chordeiles minor")
year <- paste0("1990",",","2022")
month <- paste0("3",",","6")

data.l <- list() #making empty list to store data

for (s in species) {
  obs.num <- occ_data(scientificName = s, year = year, month = month, limit = 0, country = "US", basisOfRecord = "HUMAN_OBSERVATION", stateProvince = "Massachusetts")$meta$count
  data.l[[paste0(s)]] <- occ_data(scientificName = s, year = year, month = month,
                               limit = obs.num, country = "US",
                               basisOfRecord = "HUMAN_OBSERVATION",
                               stateProvince = "Massachusetts")[[2]]
}

dat <- rbindlist(data.l,fill=T)

head(dat)

saveRDS(dat, "massbird.data.RDS")

dat%>%
  group_by(year,species)%>%
  summarise(count=sum(individualCount,na.rm = T))%>%
  ggplot(aes(x=year,y=count,col=species))+geom_point()
```

``` {r querying NOAAs NCDC API, echo = FALSE}
options(noaakey = "pXwWlsmmheEQSwUlHjihgmoZKLOCKhvE")

sts <- c(
  "GHCND:USW00013894", #Mobible, AL 2k away about 10 days away @200 km/day
  "GHCND:USW00013881", #Charlotte, NC 1000 km away about 6 days away @200 km/day
  "GHCND:USW00014739") #Boston

bos <- ncdc_stations(stationid = "GHCND:USW00014739")

sta.data <- bind_rows(
  lapply(sts,function(x) ncdc_stations(stationid = x)$data)) %>%
  mutate(usmap_transform(.,input_names = c("longitude","latitude"), output_names = c("longitude.1", "latitude.1"))) %>% #join transformation of lat/long for projection with usmap
  mutate(name = str_sub(name, -5,-4)) %>% #simplify the name column, grab just the state
  mutate(migr.day=c(10,5,0)) %>% #so we can look at wind speed 0, 5 or 10 days before arrive in boston
  separate(id,into = c("station.type","id")) #need to cut station type out from station id number

print(sta.data)

plot_usmap(include = c(.northeast_region, .south_region, .east_north_central)) + geom_point(data = sta.data, aes(x = longitude.1, y = latitude.1, col = name), size = 5) + geom_label(data = sta.data, aes(x = longitude.1, y=latitude.1, col = name, label = name), size = 5, nudge_x = 1e6*0.25) + theme(legend.position = "none")

#Now we want weather data from these stations during the spring of the years we have good data for (pretty much 2000 on)
weather.data <- meteo_pull_monitors(sta.data$id,date_min = "2000-01-01")
#tmin = minimum temperature in tenths of ºC
#tmax = maximum temperature in tenths of ºC
#awnd = average wind velocity in m^(-s)
#wdf2 = direction of fastest 2-minute wind
```

```{r preparing eBird data}
po <- dat %>%
  filter(species == "Piranga olivacea") %>%
  group_by(year) %>%
  mutate(date = as.Date(paste0(year,"-",month,"-",day)),
         j.day = julian(date,origin=as.Date(paste0(unique(year),"-01-01"))))%>%
  group_by(species, year, j.day, date) %>%
  summarise(day.tot = sum(individualCount, na.rm=T)) %>%
  group_by(species, year) %>%
  mutate(prop = cumsum(day.tot/sum(day.tot,na.rm = T))) %>%
  filter(year>1999)

po %>%
  ggplot(aes(j.day,prop)) + geom_point() + facet_wrap(year~.)

#arrival of these migrants follows a logistic process when we consider the proportion of the population that has arrived!

#lets use logistic modeling:
po.pred <- po %>%
  group_by(year) %>%
 summarize(pred = predict(nls(prop ~ SSlogis(j.day, Asym, xmid, scal)), newdata = data.frame(j.day = min(j.day):max(j.day))), #predict the logistic curve for each species
   j.day=min(j.day):max(j.day),) %>%
  left_join(po %>% dplyr::select(j.day,date)) #add date back to tibble

po %>%
  ggplot(aes(j.day,prop)) + geom_point(aes=0.3) + geom_line(data = po.pred, aes(x = j.day, y = pred), col="blue", size=2) + facet_wrap(year~.)

po.arrive.date <-po.pred%>%
  group_by(year)%>%
  filter(j.day==j.day[which.min(abs(pred-0.25))])

po.arrive.date%>%
  ggplot(aes(year,j.day))+geom_point()
```

```{r preparing weather data}
weather.data <- weather.data %>%
  mutate(year=as.integer(str_sub(date,1,4)), 
         date=as.Date(date)) %>%
  group_by(year) %>%
 mutate(j.day=julian(date,origin=as.Date(paste0(unique(year),"-01-01"))), 
  date2=date,
  wdir.rad=(180-abs(wdf2-180))*pi/180,
  wvec=cos(wdir.rad)*-1*awnd) %>% 
  dplyr::select(id,year,date2,j.day,tmin,tmax,wvec) %>% 
  left_join(sta.data %>% select(id,name,migr.day)) %>% 
  mutate(j.day=j.day+migr.day)

po.arr.weath <- po.arrive.date%>%
  left_join(weather.data)%>%
  left_join(mc%>%dplyr::select(year,date,j.day))

weather.wk <-weather.data %>% 
  group_by(year, name) %>% 
  mutate(wk.tmin = frollmean(tmin, n=14, align="right"),
         wk.tmax = frollmean(tmax, n=14, align="right"),
         wk.wvec = frollmean(wvec, n=14, align="right"))%>%
  dplyr::select(j.day,date2,name,wk.tmin,wk.tmax,wk.wvec)

po.arr.weath2 <- po.arrive.date %>%
  left_join(weather.wk)
```

```{r linear mixed effect models}

```